name: Create semantic release
description: Creates a semantic GitHub release

outputs:
  release-published:
    description: If a new release has been published
    value: ${{ steps.semantic-release.outputs.release-published }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/iron

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Copy files to context
      shell: bash
      run: |
        cp ${{ github.action_path }}/release.config.mjs .

    - id: semantic-release
      name: Create semantic release
      shell: bash
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
