name: Create semantic release
description: Creates a semantic GitHub release

outputs:
  release-published:
    description: If a new release has been published
    value: ${{ steps.semantic-release.outputs.release-published }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/iron

    - name: Install dependencies
      shell: bash
      run: npm --prefix ${{ github.action_path }} install

    - id: semantic-release
      name: Create semantic release
      shell: bash
      run: npm exec --prefix ${{ github.action_path }} semantic-release -- --extends ${{ github.action_path }}/release.config.mjs
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
